---
title: "新しい会計カリキュラム"
---


## Baldwin, Chiu, Liu, and Muehlmann (2023)

AACSBの基準A5では，会計専攻の卒業生と教員にテクノロジーアジリティが求められている。
同様に，2024年1月からの新しいUSCPA試験では，会計士が新たなテクノロジーに対応できるよう，データ分析，デジタル洞察力，テクノロジーの強固な基礎を重視することが求められている。
この記事は、テクノロジー・アジリティを導入している会計学の教授陣やプログラム・リーダーのためのリソースを提供するものである。
ビジネス・アジリティの先行指標としてのテクノロジー・アジリティの役割を説明し、会計教育者がそれを適用することが期待されるカリキュラムの構成要素について取り上げている。
教員と学生の両方における成長マインドセットについて論じている。
情報システムとデータアナリティクスの分野で共有される教育学的な懸念について説明する。
デザイン思考は、グロースマインドセット、創造的思考ツール、戦略フォローを開発するためのアプローチとして紹介される。
教員と教育ユニットのリーダーは、会計学におけるテクノロジー・アジリティを実践し、すべてのコースでそれを取り入れるよう奨励される。


## AACSB基準A5

ミッション、期待される成果、および支援戦略に沿って、会計学位プログラムには、会計およびビジネスにおける情報技術の統合に関連するスキルと知識を開発する学習経験が含まれる。これには、教員と学生の双方が、新たなテクノロジーに適応する能力だけでなく、現在のテクノロジーを使いこなす能力も含まれる。
[会計学の卒業生と教員のための情報技術スキル、敏捷性、知識]。

### 判断基準

- 目的に沿った会計学位プログラムは，カリキュラム内の3つの主要な構成要素において，現在および新たな会計及びビジネス慣行を統合している。
    - データの作成，操作・管理，セキュリティ，保存を含む情報システムとビジネスプロセス
    - 例えば，統計的手法，クラスタリング，データ管理，モデリング，分析，テキスト分析，予測分析，学習システム，視覚化などを含むデータ分析
    - 会計専門家が必要とする新しいスキルを継続的に学習する必要性を認識し，学生および教員の情報技術アジリティを開発する。
- 学習経験は，ビジネス，会計，その他の学問分野からサポートされることもある。
- 実社会のビジネス戦略，ビジネス感覚，プライバシーとセキュリティの問題，倫理的問題，情報システムとプロセス，データ管理とデータ分析ツールなどを統合的に学習する。卒業生はこれらのツールの機能とその影響，関連するリスクと機会を理解する。
- 表A-6に，各会計コースで使用されている最新技術および新技術のリストを組み込む。文書作成ソフトやプレゼンソフトのような通常のソフトは含めないこと。
- 学士課程と修士課程の両方のプログラムを提供する会計単位は、学士課程のみを提供する会計単位よりも、この基準との整合性への期待が高くなる。

### 文書化のガイダンス

- 判断の基礎として，上記の3つの主要な要素の統合を文書にする。
- 卒業生および教員にテクノロジー・アジリティを育成するコミットメントを示す。
- 関連するテクノロジー・スキル（情報システム、データ分析、データ管理、その他のビジネス情報テクノロジーなど）の学習において、会計大学院生のコンピテンシーを育成するためにユニットが導入した学習戦略と、それらがミッション、期待される成果、戦略とどのように整合しているかを文書化すること。
