---
title: "会計"
---


## Igou, Brosnan and Heavin (2023) 

デジタル革新は会計専門職を破壊しており、この破壊はさらに拡大すると思われる。
人工知能（AI）アプリケーション、ブロックチェーン、意思決定支援技術は、「誇大広告」の段階を超え、会計専門職への採用へと移行しつつある。
会計士はこれらの技術の可能性について理解を深めつつあるが、会計領域におけるこれらの新機能の活用や、それらが会計専門職にどのような影響を与えそうかについてのコンセンサスは限られている。
本研究では、新たなテクノロジーが会計士の役割に与える潜在的な影響について調査する。
これらの新興テクノロジーに関連するキーワードと、2011年から2020年の間に出版された論文に焦点を当て、関連する国際会計ジャーナル6誌のレビューを行った。
調査された論文は、会計専門職にとってデジタルな未来がどのようなものかを理解するために使用される。
本稿では、これらのテクノロジーを活用するために会計専門職がどのように変革する必要があるのか、また、会計士がデジタルトランスフォーメーションにおいてどのように不可欠な役割を果たすことができるのかを考察している。

## はじめに

デジタル技術は、1950年代初頭から会計の専門職を変革してきた。会計のための情報技術（IT）の最初の使用は、報告活動をスピードアップするために会計取引の記録を自動化することに重点を置いていた。
デジタルトランスフォーメーションの第一段階において、会計の労働力は拡大し、より多くのデジタルツールが採用されるにつれて専門知識も増大した（Zhang, Dai, and Vasarhelyi 2018）。
会計士は、単にデジタルジャーナルや元帳にデータを記録するのではなく、テクノロジーを使ってデータを情報に変換するようになった。
この変化は、多様なデジタルデータリソースを処理し理解するために、新しいスキルを持った会計士がより多く必要とされることを意味した（葉 2017）。
ここ数年、ビジネス・テクノロジーの変化率は高まっている。
こうした変化は会計士の役割を変え、管理されなければ、将来的に会計士という職業を脅かす可能性がある（Schmidt, Church, and Riley 2020）。
急速に進化するテクノロジーは、会計士という職業を大きく破壊している。
職の消滅を予測する人もいれば、大きな変化を見込む人もいる。
