---
title: "企業価値評価分析"
---

## 学習内容

- 企業価値評価の理論と手法を学ぶ
- 資本コストを理解する
- DDM, DCF, RIMを理解する

## 企業価値とは

投資家の究極的な目標は会社の価値を知ることにあります。
株式投資家がある企業の株式を購入する際，投資家はその株価が企業の価値と比べて高いのか安いのかを検討します。
株価が安ければ購入し，高ければ購入を見送るでしょう。
債権者であれば，お金を貸す企業が倒産せずに元本と利息をしっかり払ってくれるかどうかを知りたいはずです。

企業価値が重要であることが分かったとして，ではそれをどうやって測るのか，というのは難しい問題です。
経営者にとっての価値，従業員にとっての価値，債権者にとっての価値，株主にとっての価値，そして国にとっての価値はすべて異なるでしょう。
したがって，企業価値を測定する唯一の方法など存在しません。

そこで，ここでは株主から見た企業価値と，出資者全体からみた企業価値の2つの企業価値を測定する方法をみていきます。

## 株主からみた企業価値

株主は，株式会社が発行する株式を保有することで，インカムゲインである配当とキャピタルゲインである値上がり益を期待します。
たとえば，0時点で株式を購入し，1期間株式を保有し，1時点で配当$D_1$を受け取り，株式を$P_1$で売却したとします。
この株主が1時点で受け取る利得は，

$$
D_1 + P_1
$$

です。
この現在価値を計算します。ここで割引率(資本コスト)を$r$とします。
すると，この株式がもたらす利得の現在価値$PV_0$は，
$$
PV_0 = \frac{D_1 + P_1}{1 + r}
$$

で計算できます。
市場が効率的であれば，投資家はこの現在価値で株式を購入します。

:::{.column-margin}
もし$PV_0$より高い株価$PV_a$がついているとしましょう。
その場合，この投資のNPVは$PV_0 - PV_a < 0$となり，投資すべきでないという判断となります。
もし$PV_0$より低い株価$PV_b$がついているとしましょう。
この場合，投資のNPVは$PV_0 - PV_a > 0$となり投資すべき対象といえます。
そして投資から利益がでるため，多くの投資家がこの株式を買おうとするでしょう。その結果$PV_0$になるまで株価が増加し，結局$PV_0$でしか株式を買うことが出来なくなります。
:::

では，2期間株式を保有する場合の株式投資の現在価値を考えてみましょう。

$$
PV_0 = \frac{D_1}{1 + r} + \frac{D_2 + P_2}{(1+r)^2}
$$

最後に$N$期間，株式を保有する場合の投資の現在価値を考えてみましょう。

$$
PV_0 = \frac{D_1}{1 + r} + \frac{D_2}{(1+r)^2} + \cdots + \frac{D_N}{(1+r)^N} + \frac{P_N}{(1+r)^N}
$$

保有期間$N$が十分に長い場合，上の式の最後の項である

$$
\lim _{N\rightarrow \infty} \frac{P_N}{(1+r)^N} = 0
$$

は限りなく0の値に近づいていきます。
そこで，最後の項を無視できるほど十分長い期間，株式を保有する場合，上の$N$期間モデルは，次のようにまとめることができます。

$$
PV_0 = \sum _{t = 1}^N \frac{D_t}{(1+r)^t}
$$
この将来の配当の現在価値が，株式投資の価値を表す，というモデルを配当割引モデル(discounted dividend model: DDM)といいます。

この配当割引モデルは将来に受け取れるであろう配当額を予想
